server {
    listen 80 default_server reuseport;
    listen [::]:80 default_server reuseport;

    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    server_name _;
    http2 on;

    # SSL Config
    ssl_certificate /etc/letsencrypt/live/test-name/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/test-name/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/test-name/chain.pem;
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location / {
        # If the request is plain HTTP, redirect to HTTPS
        if ($scheme = "http") {
            return 301 https://$http_host$request_uri;
        }

        # If it's already HTTPS but reached this 'default' block,
        # it means the domain didn't match any of your other sites.
        return 444;
    }
}